version: "1.1.0"
databases:
  - name: swarmdb
    entities:
      - name: LeadershipProposal
        primary_key: id
        fields:
          - name: id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: epoch
            type: lww_register
            sql_type: INTEGER
            required: true
          - name: node_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: hlc
            type: lww_register
            sql_type: TEXT
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: lease_until_ts
            type: timestamp
            sql_type: BIGINT
          - name: leader_score
            type: lww_register
            sql_type: REAL
      - name: LeadershipPointer
        primary_key: id
        fields:
          - name: id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: epoch
            type: lww_register
            sql_type: INTEGER
            required: true
          - name: node_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: hlc
            type: lww_register
            sql_type: TEXT
          - name: lease_until_ts
            type: timestamp
            sql_type: BIGINT
      - name: LeadershipAttestation
        primary_key: id
        fields:
          - name: id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: epoch
            type: lww_register
            sql_type: INTEGER
            required: true
          - name: node_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: expires_ts
            type: timestamp
            sql_type: BIGINT
      - name: PrevoteBallot
        primary_key: ballot_epoch
        fields:
          - name: ballot_epoch
            type: lww_register
            sql_type: INTEGER
            required: true
          - name: node_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: hlc
            type: lww_register
            sql_type: TEXT
          - name: deadline_ts
            type: timestamp
            sql_type: BIGINT
          - name: score
            type: lww_register
            sql_type: REAL
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
      - name: PrevoteAttestation
        primary_key: id
        fields:
          - name: id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: ballot_epoch
            type: lww_register
            sql_type: INTEGER
            required: true
          - name: node_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: expires_ts
            type: timestamp
            sql_type: BIGINT
      - name: QuorumPolicy
        primary_key: id
        fields:
          - name: id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: policy_json
            type: lww_register
            sql_type: TEXT
            required: true
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT
      - name: Measurement
        primary_key: id
        fields:
          - name: id # node_id:type:target_node_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: type
            type: lww_register
            sql_type: TEXT
            required: true
          - name: node # link to Node
            type: lww_register
            sql_type: TEXT
            required: true
          - name: target_node # link to Node
            type: lww_register
            sql_type: TEXT
            required: true
          - name: value
            type: lww_register
            sql_type: TEXT
            required: true
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT
          - name: deleted_ts
            type: timestamp
            sql_type: BIGINT
      - name: ClusterPolicy
        primary_key: id
        fields:
          - name: id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: minSize
            type: lww_register
            sql_type: INTEGER
            required: false
          - name: maxSize
            type: lww_register
            sql_type: INTEGER
            required: false
          - name: maxClusters
            type: lww_register
            sql_type: INTEGER
            required: false
      - name: ClusterPolicyMeasurementRule
        primary_key: id # cluster_policy_name:name
        fields:
          - name: id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster_policy # link to ClusterPolicy
            type: lww_register
            sql_type: TEXT
            required: true
          - name: measurement_type
            type: lww_register
            sql_type: TEXT
            required: true
          - name: condition
            type: lww_register
            sql_type: TEXT
            required: true
          - name: value
            type: lww_register
            sql_type: TEXT
            required: true
          - name: jitter
            type: lww_register
            sql_type: INTEGER
            required: true
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT
          - name: deleted_ts
            type: timestamp
            sql_type: BIGINT
      - name: ClusterPolicyAffinityRule
        primary_key: id # cluster_policy_name:name
        fields:
          - name: id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster_policy # link to ClusterPolicy
            type: lww_register
            sql_type: TEXT
            required: true
          - name: target_cluster_policy # link to ClusterPolicy
            type: lww_register
            sql_type: TEXT
            required: true
          - name: affinity_type
            type: lww_register
            sql_type: TEXT
            required: true
      - name: Cluster
        primary_key: id
        fields:
          - name: id # cluster_policy_id:uuid
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster_policy
            type: lww_register
            sql_type: TEXT
            required: true
          - name: leader_node # link to Node
            type: lww_register
            sql_type: TEXT
            required: false
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT
          - name: deleted_ts
            type: timestamp
            sql_type: BIGINT
      - name: ClusterNode
        primary_key: id
        fields:
          - name: id # cluster_id:node_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster # link to Cluster
            type: lww_register
            sql_type: TEXT
            required: true
          - name: node # link to Node
            type: lww_register
            sql_type: TEXT
            required: true
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: deleted_ts
            type: timestamp
            sql_type: BIGINT
      - name: ClusterProperty
        primary_key: id
        fields:
          - name: id # cluster_id:name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster # link to Cluster
            type: lww_register
            sql_type: TEXT
            required: true
          - name: name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: value
            type: lww_register
            sql_type: TEXT
            required: true
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT
          - name: deleted_ts
            type: timestamp
            sql_type: BIGINT
      - name: ClusterNodeProperty
        primary_key: id
        fields:
          - name: id # cluster_node_id:name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster_node # link to ClusterNode
            type: lww_register
            sql_type: TEXT
            required: true
          - name: name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: value
            type: lww_register
            sql_type: TEXT
            required: true
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT
          - name: deleted_ts
            type: timestamp
            sql_type: BIGINT

      # Describes a deployable service (plugin) bound to a cluster policy.
      # Stores the manifest (including jq/gojq plan expression) and where to obtain the plugin bits.
      - name: ClusterService
        primary_key: id
        fields:
          - name: id                 # <cluster_policy>:<service_name>
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster_policy     # link to ClusterPolicy
            type: lww_register
            sql_type: TEXT
            required: true
          - name: name               # service plugin name (e.g., rke2, minio)
            type: lww_register
            sql_type: TEXT
            required: true
          - name: version            # manifest/plugin version
            type: lww_register
            sql_type: TEXT
            required: true
          - name: location           # where to fetch/execute (docker://..., file://..., wasi://...)
            type: lww_register
            sql_type: TEXT
            required: true
          - name: hash               # optional bundle/content hash for integrity
            type: lww_register
            sql_type: TEXT
          - name: manifest           # full YAML manifest including stateExpr / schema
            type: lww_register
            sql_type: TEXT
            required: true
          - name: created_ts
            type: timestamp
            sql_type: BIGINT
          - name: updated_ts         # last update timestamp (unix millis)
            type: timestamp
            sql_type: BIGINT

      # Lightweight, cluster-scoped digest of the computed plan for a service.
      # Nodes recompute the plan locally and compare against this digest to detect changes.
      - name: ClusterServicePlanDigest
        primary_key: id
        fields:
          - name: id                 # <cluster_id>:<service_name>
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: service_name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: plan_epoch         # monotonically increasing epoch when plan_hash changes
            type: lww_register
            sql_type: INTEGER
            required: true
          - name: plan_hash          # sha256 over canonicalized plan JSON (e.g., JCS)
            type: lww_register
            sql_type: TEXT
            required: true
          - name: plan_inputs_hash   # hash of (expr code + read set digest), for safety
            type: lww_register
            sql_type: TEXT
            required: true
          - name: read_set_digest    # digest of collections read during jq query execution
            type: lww_register
            sql_type: TEXT
          - name: produced_by        # node_id that first published this digest
            type: lww_register
            sql_type: TEXT
          - name: produced_hlc       # HLC timestamp used for LWW arbitration
            type: lww_register
            sql_type: TEXT
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT

      # Cluster-wide coarse-grained service status used for coordination (e.g., leader-first bootstrap).
      - name: ClusterServiceStatus
        primary_key: id
        fields:
          - name: id                 # <cluster_id>:<service_name>
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: service_name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: phase              # Pending|Bootstrapping|Ready|Degraded|Deleting
            type: lww_register
            sql_type: TEXT
            required: true
          - name: reason             # short reason for current phase (human-readable)
            type: lww_register
            sql_type: TEXT
          - name: leader_node        # node_id expected to run bootstrap-first (if applicable)
            type: lww_register
            sql_type: TEXT
          - name: blockers_json      # JSON array of blockers (e.g., [{"type":"bootstrap","until":...}])
            type: lww_register
            sql_type: TEXT
          - name: observed_plan_epoch  # last plan epoch the cluster service converged to
            type: lww_register
            sql_type: INTEGER
          - name: ready_nodes_count  # count of nodes with phase=Ready
            type: lww_register
            sql_type: INTEGER
          - name: total_nodes_count  # total count of nodes in cluster
            type: lww_register
            sql_type: INTEGER
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT

      # Per-node lightweight status for the service inside a cluster.
      # Keeps heartbeat and high-level phase only (detailed health stays local).
      - name: ClusterServiceNodeStatus
        primary_key: id
        fields:
          - name: id                 # <cluster_id>:<service_name>:<node_id>
            type: lww_register
            sql_type: TEXT
            required: true
          - name: cluster_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: service_name
            type: lww_register
            sql_type: TEXT
            required: true
          - name: node_id
            type: lww_register
            sql_type: TEXT
            required: true
          - name: phase              # Applying|Waiting|Ready|Degraded|Draining|Deleted
            type: lww_register
            sql_type: TEXT
            required: true
          - name: observed_plan_epoch
            type: lww_register
            sql_type: INTEGER
          - name: last_heartbeat_ts  # unix millis; used to detect stale nodes
            type: timestamp
            sql_type: BIGINT
          - name: short_msg          # brief hint (<= ~400 bytes), no verbose logs
            type: lww_register
            sql_type: TEXT
          - name: last_apply_status  # completed|error|postponed for last apply command
            type: lww_register
            sql_type: TEXT
          - name: postpone_count     # number of consecutive postpone responses
            type: lww_register
            sql_type: INTEGER
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT

      # Bootstrap lease for leader-first workflows (e.g., RKE2 server token/materials).
      # Implemented as LWW with lease_until_ts to avoid split-brain.
      - name: ServiceBootstrapLease
        primary_key: id
        fields:
          - name: id                 # <cluster_id>:<service_name>
            type: lww_register
            sql_type: TEXT
            required: true
          - name: holder             # node_id currently holding the lease
            type: lww_register
            sql_type: TEXT
          - name: lease_until_ts     # unix millis; considered free after this timestamp
            type: timestamp
            sql_type: BIGINT
          - name: epoch              # associated plan epoch for which the lease applies
            type: lww_register
            sql_type: INTEGER
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT

      # Cluster-scoped secret/artifact references (encrypted payload; policy-gated by attestation).
      - name: SecretArtifact
        primary_key: id
        fields:
          - name: id                 # e.g., Secret:<cluster>/<service>/<key>:<epoch>
            type: lww_register
            sql_type: TEXT
            required: true
          - name: type               # rke2-token|tls|jwt|opaque|...
            type: lww_register
            sql_type: TEXT
            required: true
          - name: payload            # secret payload
            type: lww_register
            sql_type: TEXT
            required: true
          - name: policy_json        # attestation/access policy (TDX measurements, roles, etc.)
            type: lww_register
            sql_type: TEXT
          - name: expires_ts
            type: timestamp
            sql_type: BIGINT
          - name: updated_ts
            type: timestamp
            sql_type: BIGINT
