#!/usr/bin/env python3
"""YAML side of cluster.sh: the cluster specification and per-node provider_config.

Subcommands (each prints JSON or plain text for cluster.sh to consume):

  spec <spec.yaml> [--release TAG] [--provider-config DIR]
      Validate the cluster specification and print it normalized as JSON:
      every node carries all of its fields, paths are absolute.

  node <defaults.json> <key=value,...>
      Merge one --node argument of `cluster.sh add` over the defaults and print
      the node as JSON.

  render --template DIR --out DIR --node-name NAME --role bootstrap|join
         [--peer IP]... [--ca FILE] [--swarm-domain D] [--pki-domain D]
      Copy the provider_config template to DIR and set the node-specific fields
      of swarm/config.yaml. Prints the node's swarm_domain.

  check-ca <ca.pem>
      Fail unless the bundle holds exactly one self-signed root.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

import yaml

CLUSTER_NAME_RE = re.compile(r"^[a-z][a-z0-9-]{1,30}$")
NODE_FIELDS = ("size", "location", "zone", "state_disk_size")
GOSSIP_PORT = 7946
PKI_PORT = 9443
MIN_NODES = 3


def fail(message):
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)


def normalize_node(raw, defaults, where):
    if raw is None:
        raw = {}
    if not isinstance(raw, dict):
        fail(f"{where}: a node must be a mapping of {', '.join(NODE_FIELDS)}")
    unknown = set(raw) - set(NODE_FIELDS)
    if "name" in unknown:
        fail(f"{where}: node names are generated by cluster.sh and cannot be set")
    if unknown:
        fail(f"{where}: unknown field(s) {', '.join(sorted(unknown))}; allowed: {', '.join(NODE_FIELDS)}")
    node = {**defaults, **raw}
    missing = [field for field in NODE_FIELDS if node.get(field) in (None, "")]
    if missing:
        fail(f"{where}: missing {', '.join(missing)} (set them on the node or in defaults)")
    node["size"] = str(node["size"])
    node["location"] = str(node["location"])
    node["zone"] = str(node["zone"])
    if not re.fullmatch(r"[1-9]", node["zone"]):
        fail(f"{where}: zone must be a single digit, got {node['zone']!r}")
    try:
        node["state_disk_size"] = int(node["state_disk_size"])
    except (TypeError, ValueError):
        fail(f"{where}: state_disk_size must be a number of GB, got {node['state_disk_size']!r}")
    if node["state_disk_size"] < 0:
        fail(f"{where}: state_disk_size must not be negative")
    return {field: node[field] for field in NODE_FIELDS}


def cmd_spec(args):
    with open(args.spec, encoding="utf-8") as f:
        spec = yaml.safe_load(f) or {}
    if not isinstance(spec, dict):
        fail(f"{args.spec}: the specification must be a mapping")
    allowed = {"name", "release", "provider_config", "defaults", "nodes", "swarm_domain", "pki_domain"}
    unknown = set(spec) - allowed
    if unknown:
        fail(f"{args.spec}: unknown key(s) {', '.join(sorted(unknown))}")

    name = str(spec.get("name") or "")
    if not CLUSTER_NAME_RE.fullmatch(name):
        fail(f"{args.spec}: name must match {CLUSTER_NAME_RE.pattern}, got {name!r}")

    release = args.release or spec.get("release")
    if not release:
        fail(f"{args.spec}: no release (set `release` or pass --release)")

    spec_dir = os.path.dirname(os.path.abspath(args.spec))
    template = args.provider_config or spec.get("provider_config")
    if not template:
        fail(f"{args.spec}: no provider_config (set it or pass --provider-config)")
    if not os.path.isabs(template) and not args.provider_config:
        template = os.path.join(spec_dir, template)
    template = os.path.abspath(template)
    if not os.path.isfile(os.path.join(template, "swarm", "config.yaml")):
        origin = "--provider-config" if args.provider_config else \
            f"provider_config in {args.spec} (a relative path is resolved against the specification's directory)"
        fail(f"{template}/swarm/config.yaml not found; check {origin}")

    defaults = spec.get("defaults") or {}
    if not isinstance(defaults, dict):
        fail(f"{args.spec}: defaults must be a mapping")
    bad = set(defaults) - set(NODE_FIELDS)
    if bad:
        fail(f"{args.spec}: unknown field(s) in defaults: {', '.join(sorted(bad))}")

    nodes = spec.get("nodes")
    if not isinstance(nodes, list) or len(nodes) < MIN_NODES:
        fail(f"{args.spec}: nodes must list at least {MIN_NODES} machines (bootstrap first)")
    nodes = [normalize_node(raw, defaults, f"{args.spec}: nodes[{i}]") for i, raw in enumerate(nodes)]

    print(json.dumps({
        "name": name,
        "release": str(release),
        "provider_config": template,
        "defaults": defaults,
        "nodes": nodes,
        "swarm_domain": spec.get("swarm_domain") or "",
        "pki_domain": spec.get("pki_domain") or "",
    }, indent=2))


def cmd_node(args):
    with open(args.defaults, encoding="utf-8") as f:
        defaults = json.load(f)
    raw = {}
    for item in filter(None, (part.strip() for part in args.fields.split(","))):
        key, sep, value = item.partition("=")
        if not sep:
            fail(f"--node: expected key=value, got {item!r}")
        raw[key.strip()] = value.strip()
    print(json.dumps(normalize_node(raw, defaults, "--node")))


class _Dumper(yaml.SafeDumper):
    pass


def _str_representer(dumper, data):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_Dumper.add_representer(str, _str_representer)


def cmd_render(args):
    config_path = os.path.join(args.template, "swarm", "config.yaml")
    if not os.path.isfile(config_path):
        fail(f"{config_path} not found")

    if os.path.exists(args.out):
        shutil.rmtree(args.out)
    shutil.copytree(args.template, args.out)
    os.chmod(args.out, 0o700)

    out_config = os.path.join(args.out, "swarm", "config.yaml")
    with open(out_config, encoding="utf-8") as f:
        cfg = yaml.safe_load(f) or {}

    swarm_db = cfg.setdefault("swarm_db", {}) or {}
    cfg["swarm_db"] = swarm_db
    pki = cfg.get("pki_authority") or {}
    cfg["pki_authority"] = pki
    if not pki.get("networkID"):
        fail(f"{config_path}: pki_authority.networkID is not set; every node of a Swarm needs the same one")

    swarm_db["node_name"] = args.node_name
    # The VM detects its own public address; a template value would be wrong
    # for every node but one.
    swarm_db.pop("advertise_addr", None)

    if args.swarm_domain:
        cfg["swarm_domain"] = args.swarm_domain
    if args.pki_domain:
        cfg["pki_domain"] = args.pki_domain

    # detect_swarm_pki_state() (pki_configure_helper.py) accepts only two
    # shapes: all three fields empty (init) or all three set (normal).
    if args.role == "bootstrap":
        if args.peer or args.ca:
            fail("a bootstrap node takes no --peer and no --ca")
        swarm_db["join_addresses"] = []
        pki.pop("caBundle", None)
        pki.pop("servers", None)
    else:
        if not args.peer or not args.ca:
            fail("a join node needs at least one --peer and --ca")
        with open(args.ca, encoding="utf-8") as f:
            ca = f.read().strip()
        swarm_db["join_addresses"] = [f"{ip}:{GOSSIP_PORT}" for ip in args.peer]
        pki["caBundle"] = ca + "\n"
        pki["servers"] = [f"{ip}:{PKI_PORT}" for ip in args.peer]

    with open(out_config, "w", encoding="utf-8") as f:
        yaml.dump(cfg, f, Dumper=_Dumper, sort_keys=False, default_flow_style=False)

    print(cfg.get("swarm_domain") or "")


def cmd_check_ca(args):
    with open(args.ca, encoding="utf-8") as f:
        if "BEGIN CERTIFICATE" not in f.read():
            fail(f"{args.ca} does not look like a PEM certificate bundle")
    pkcs7 = subprocess.run(["openssl", "crl2pkcs7", "-nocrl", "-certfile", args.ca],
                           capture_output=True, text=True, check=True).stdout
    listing = subprocess.run(["openssl", "pkcs7", "-print_certs", "-noout"],
                             input=pkcs7, capture_output=True, text=True, check=True).stdout
    subjects = [line[len("subject="):] for line in listing.splitlines() if line.startswith("subject=")]
    issuers = [line[len("issuer="):] for line in listing.splitlines() if line.startswith("issuer=")]
    roots = sum(1 for subject, issuer in zip(subjects, issuers) if subject == issuer)
    if roots != 1:
        fail(f"{args.ca}: expected exactly one self-signed root, found {roots}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("spec")
    p.add_argument("spec")
    p.add_argument("--release")
    p.add_argument("--provider-config")
    p.set_defaults(func=cmd_spec)

    p = sub.add_parser("node")
    p.add_argument("defaults")
    p.add_argument("fields")
    p.set_defaults(func=cmd_node)

    p = sub.add_parser("render")
    p.add_argument("--template", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--node-name", required=True)
    p.add_argument("--role", required=True, choices=("bootstrap", "join"))
    p.add_argument("--peer", action="append", default=[])
    p.add_argument("--ca")
    p.add_argument("--swarm-domain")
    p.add_argument("--pki-domain")
    p.set_defaults(func=cmd_render)

    p = sub.add_parser("check-ca")
    p.add_argument("ca")
    p.set_defaults(func=cmd_check_ca)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
