logging:
  providers:
    pino:
      type: pino
  currentLogger: pino
  level: debug

api:
    enabled: true
    endpoints:
    - https://127.0.0.1:443
    - http://127.0.0.1:80
    enabledApis:
    - secrets
    - pki
pki:
  baseDomain: ca-subroot.super-protocol.svc.cluster.local
  allowedChallenges:
    - token
    - tdx
    - sev-snp
  validateParamRules:
    - type: tdx
      signatureVerification: github
    - type: sev-snp
      signatureVerification: github
  allowedOcspSignerChallenges: []
  tokenStorage:
    storageType: file
    storageFolder: /app/swarm-storage
  certParams:
    lifetimeDays: 3650
    commonName: 'SuperProtocol TEE SubRoot CA'
    countryName: 'US'
    stateName: 'NY'
    localityName: 'New York'
    organizationName: 'SuperProtocol'
    organizationUnitName: 'IT'
    ocspUrl: ''
  httpsCertificateType:
    type: PKI
  mode:
    role: swarm
    storage:
      storageType: file
      storageFolder: /app/swarm-storage
    networkSettings:
      networkType: trusted
      networkID: dummy-network-key

secretsStorage:
  static:
    swarmKey: dummy-swarm-key
  storage:
    storageType: file
    storageFolder: /app/swarm-storage
  validationCaBundle:
    type: pki
