name: Build SuperProtocol OS image
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      target-branch:
        required: true
        type: string
        description: sp-kata-containers branch
        default: "sp-main"
      runs-on:
        required: true
        type: choice
        description: github runner for build
        options:
        - sp-vm-runner
        - ubuntu-latest

jobs:
  build-asset:
    runs-on: ${{ inputs.runs-on }}

    steps:
      - name: Checkout another repository
        uses: actions/checkout@v4
        with:
          repository: Super-Protocol/sp-kata-containers
          path: sp-kata-containers
          fetch-depth: 0
          ref: ${{ inputs.target-branch }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        working-directory: sp-kata-containers
        run: |
          sudo apt-get update
          sudo apt-get -y install curl
          sudo bash -c ./sp-build.sh
          sudo rm -rf build/rootfs
