#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_IMAGE="python:3.12-slim@sha256:57cd7c3a7a273101a6485ba99423ee568157882804b1124b4dd04266317710de"
PIP_TOOLS_VERSION="7.5.3"
WORK_DIR="$(mktemp -d -t sp-vm-python-lock.XXXXXXXX)"

function cleanup() {
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

mkdir -p "$WORK_DIR/wheels"

docker run --rm --platform linux/amd64 \
    --volume "$SCRIPT_DIR/requirements.in:/input/requirements.in:ro" \
    --volume "$WORK_DIR:/work" \
    "$PYTHON_IMAGE" \
    sh -euc "
        python -m pip install --disable-pip-version-check --quiet pip-tools==$PIP_TOOLS_VERSION
        pip-compile \
            --generate-hashes \
            --quiet \
            --resolver=backtracking \
            --strip-extras \
            --output-file=/work/requirements.full.lock \
            /input/requirements.in
        python -m pip download \
            --disable-pip-version-check \
            --only-binary=:all: \
            --require-hashes \
            --requirement /work/requirements.full.lock \
            --dest /work/wheels
    "

python3 - "$WORK_DIR/wheels" "$SCRIPT_DIR/requirements.lock" <<'PY'
import email
import hashlib
import pathlib
import sys
import zipfile

wheel_dir = pathlib.Path(sys.argv[1])
output_path = pathlib.Path(sys.argv[2])
requirements = []

for wheel in wheel_dir.glob("*.whl"):
    digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
    with zipfile.ZipFile(wheel) as archive:
        metadata_path = next(
            name for name in archive.namelist() if name.endswith(".dist-info/METADATA")
        )
        metadata = email.message_from_bytes(archive.read(metadata_path))
    requirements.append((metadata["Name"], metadata["Version"], digest))

requirements.sort(key=lambda item: item[0].lower())
lines = [
    "# Locked for CPython 3.12 on Linux amd64.",
    "# Generated by update-lock.sh; each package permits one selected wheel.",
    "",
]
for name, version, digest in requirements:
    lines.extend((f"{name}=={version} \\", f"    --hash=sha256:{digest}"))

output_path.write_text("\n".join(lines) + "\n")
PY

echo "Updated $SCRIPT_DIR/requirements.lock"
